apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: secret-store-sa@{{ .Values.cluster.projectID }}.iam.gserviceaccount.com
  name: secret-store-sa
  namespace: {{ .Release.Namespace }}
