apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: secretstore
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.cluster.projectID }}
      auth:
        workloadIdentity:
          clusterLocation: {{ .Values.cluster.region }}
          clusterName: {{ .Values.cluster.clusterName }}
          serviceAccountRef:
            name: secret-store-sa
            namespace: {{ .Release.Namespace }}
