apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fhirserver-db-password
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: secretstore
    kind: ClusterSecretStore
  target:
    name: fhirserver-db-password
    creationPolicy: Owner
  data:
    - secretKey: fhirserver-db-password
      remoteRef:
        key: fhirserver-db-password
