apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: auth0-client-secret
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: secretstore
    kind: ClusterSecretStore
  target:
    name: auth0-client-secret
    creationPolicy: Owner
  data:
    - secretKey: auth0-client-secret
      remoteRef:
        key: auth0-client-secret
