apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-secret-webapp
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: secretstore
    kind: ClusterSecretStore
  target:
    name: webapp-db-url
    creationPolicy: Owner
  data:
    - secretKey: webapp-db-url
      remoteRef:
        key: webapp-db-url
