apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: form-parser-processor-id-secret
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: secretstore
    kind: ClusterSecretStore
  target:
    name: form-parser-processor-id-secret
    creationPolicy: Owner
  data:
    - secretKey: form-parser-processor-id-secret
      remoteRef:
        key: form-parser-processor-id-secret
