apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gcp-creds-secret
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: secretstore
    kind: ClusterSecretStore
  target:
    name: gcp-creds-secret
    creationPolicy: Owner
  data:
    - secretKey: gcp-creds-secret
      remoteRef:
        key: gcp-creds-secret
