apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextauth-secret
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: secretstore
    kind: ClusterSecretStore
  target:
    name: nextauth-secret
    creationPolicy: Owner
  data:
    - secretKey: nextauth-secret
      remoteRef:
        key: nextauth-secret
