apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ocr-processor-id-secret
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: secretstore
    kind: ClusterSecretStore
  target:
    name: ocr-processor-id-secret
    creationPolicy: Owner
  data:
    - secretKey: ocr-processor-id-secret
      remoteRef:
        key: ocr-processor-id-secret
