apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openai-api-secret
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: secretstore
    kind: ClusterSecretStore
  target:
    name: openai-api-secret
    creationPolicy: Owner
  data:
    - secretKey: openai-api-secret
      remoteRef:
        key: openai-api-secret
