apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-port-secret
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: secretstore
    kind: ClusterSecretStore
  target:
    name: redis-port-secret
    creationPolicy: Owner
  data:
    - secretKey: redis-port-secret
      remoteRef:
        key: redis-port-secret
