apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dd-api-key
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: secretstore
    kind: ClusterSecretStore
  target:
    name: dd-api-key
    creationPolicy: Owner
  data:
    - secretKey: dd-api-key
      remoteRef:
        key: dd-api-key

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dd-app-key
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: secretstore
    kind: ClusterSecretStore
  target:
    name: dd-app-key
    creationPolicy: Owner
  data:
    - secretKey: dd-app-key
      remoteRef:
        key: dd-app-key
