apiVersion: v2
name: nginx-ingress-controller
description: A Helm chart for External Secrets Operator


type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: "external-secrets"
    version: "0.7.2"
    repository: "https://charts.external-secrets.io"