apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-actions-pat
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: secretstore
    kind: ClusterSecretStore
  target:
    name: {{ .Values.authSecretName }}
    creationPolicy: Owner
  data:
    - secretKey: github_token
      remoteRef:
        key: github-actions-personal-access-token