name: Deploy enduesoftware.com to Aptible

on:
  push:
    branches: [ "master" ]
    paths: [ "frontend/main-website/**" ]

env:
  APTIBLE_ENVIRONMENT: endue-prod
  APTIBLE_APP: website-staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.APTIBLE_GIT_SSH_KEY }}
      - name: Deploy to Aptible
        run: |
          ssh-keyscan beta.aptible.com >> ~/.ssh/known_hosts
          cd frontend/main-website
          git init
          git config --global user.email ${{ secrets.ENDUE_EMAIL }}
          git config --global user.name ${{ secrets.MY_NAME }}
          git add --all
          git commit -m "Deploy enduesoftware.com to Aptible"
          git remote add aptible git@beta.aptible.com:${APTIBLE_ENVIRONMENT}/${APTIBLE_APP}.git
          git push aptible master
